language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  api_key:
    secure: TlLDvS54VcJ3Jt6fE561PezNOX9XU5tiAG0E24/LANZZP4o4ejqe0PnkR1JB8IL8+b1u1cWTin0pHiT97IxPJsSOTcND3cQCK4ERz8G1Fq6rIhYKbhR0gxYXr0ITXQjyQjpP3+Z26OpmfRZOKk+ODGhqu+54E8b8WxsXAcWlH40Kn5wUo2XEIRPhdn5MY6mr0B0CekjIjuktyhHFkoleMu0y+bo4kOEPbfE0/YziyGTXTQ770dgbszsOQ+yWVEBZcVS4iGAKVIV9NdjAfVAYJb/3Vh/iuwnBOJ6oo7FeYuctdD9cc5w9xudxaULqe0cR+2x+dzC4PtnzoYKcXgXBOmrdiK9vzUCxEVYSgZoCdoBndZCBPJHpzf5YU1XwYqxd95QzRkZx7nAqb8HrIjpwpkU35uLWXWa8vM+2po008TC60LVrcHc24fpy3VUxMDQ64z3VqILRbm09QVH4vMQUtyQdQgMyExi97AjrTqHHeWIuKdEatrQHZSH+kRfoqbN/EiIhg6DtdGTWhUuFgLgt/EWelHIgtJAzPSGrbuLIgCRaavM7xOP6A3GIOWcbH/E4Kygux+cGs1vznqxQ/Mv4DQjmgNrE0iLh0dH0Jt5VD01eHuKulzf/g+kXTIwzx2tNHm0A/ML85bV3Bq/svQvurSgTatTa3lork12O2Av07TI=
    app: rancid-tomatillos-practive
    skip_cleanup: true